project:
  type: website
  output-dir: ../docs

website:
  title: "Pheno.AI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: datasets.md
        text: Available Datasets
      - platform_tutorial.md
      - publications.md
      
  sidebar:
    style: "docked"
    search: true
    contents:
      - platform_tutorial.md
      - pheno_utils.md
      - faq.md
      - data_format.qmd
      - section: "Datasets"
        contents:
          - href: datasets.md
            text: Available Datasets
          - datasets/000-population.ipynb
          - datasets/001-events.ipynb
          - datasets/002-anthropometrics.ipynb
          - datasets/003-fundus.ipynb
          - datasets/004-liver_ultrasound.ipynb
          - datasets/005-diet_logging.ipynb
          - datasets/006-hand_grip.ipynb
          - datasets/007-blood_pressure.ipynb
          - datasets/008-serum_lipidomics.ipynb
          - datasets/009-sleep.ipynb
          - datasets/010-vascular_health.ipynb
          - datasets/011-body_composition.ipynb
          - datasets/012-carotid_ultrasound.ipynb
          - datasets/013-gut_microbiome.ipynb
          - datasets/014-human_genetics.ipynb
          - datasets/015-ecg.ipynb
          - datasets/016-blood_tests.ipynb
          - datasets/017-cgm.ipynb
          - datasets/018-medications.ipynb
          - datasets/021-medical_conditions.ipynb
          - datasets/022-bone_density.ipynb
          - datasets/040-ukbb_questionnaire.ipynb
          - datasets/041-ukbb_followup_questionnaire.ipynb
          - datasets/042-ibs_questionnaire.ipynb
          - datasets/043-covid_questionnaire.ipynb


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



